version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  redisinsight:
    image: redislabs/redisinsight:2.70
    ports:
      - "5540:5540"
volumes:
  redis_data:
